ALTER TABLE users ADD COLUMN IF NOT EXISTS github_id VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_username VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_access_token VARCHAR;
