"""Marketplace listing model."""
from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, JSON, Numeric, String, Text
from sqlalchemy.orm import relationship
from datetime import datetime
from db.session import Base
import uuid


class Listing(Base):
    __tablename__ = "listings"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    vendor_id = Column(String, ForeignKey("vendors.id"), nullable=False, index=True)
    workspace_id = Column(String, ForeignKey("workspaces.id"), nullable=False, index=True)

    # Identity
    title = Column(String, nullable=False)
    slug = Column(String, nullable=True, index=True)
    description = Column(Text, nullable=True)
    summary = Column(Text, nullable=True)  # auto-generated by LLM classifier
    version = Column(String, nullable=False, default="1.0.0")

    # Discovery (auto-classifier fills these on submit)
    listing_type = Column(String, nullable=False, default="pipeline", index=True)
    # values: pipeline | tool | prompt_pack | dataset | agent | connector | evidence_pack | edge_template
    category = Column(String, nullable=True, index=True)
    # values: legal | medical | finance | compliance | infra | edge_industrial | general
    tags = Column(JSON, nullable=True)  # list[str]

    # Commerce
    price_cents = Column(Integer, nullable=False, default=0)
    currency = Column(String, nullable=False, default="usd")
    status = Column(String, nullable=False, default="draft", index=True)  # draft|pending_review|active|rejected|disabled

    # Install — what actually gets created in the buyer's workspace.
    install_payload = Column(JSON, nullable=True)  # pipeline graph / tool spec / prompt template / etc.

    # Trust & social proof
    install_count = Column(Integer, nullable=False, default=0, index=True)
    rating_avg = Column(Float, nullable=False, default=0.0)
    rating_count = Column(Integer, nullable=False, default=0)
    is_featured = Column(Boolean, nullable=False, default=False, index=True)

    # Compliance & cost cards
    compliance_badges = Column(JSON, nullable=True)  # list[str] e.g. ["EU-sovereign", "HIPAA-aware", "SOC2-evidence"]
    predicted_cost_per_run = Column(Numeric(10, 6), nullable=True)  # cached from /cost/predict

    # Automation flags
    auto_classified = Column(Boolean, nullable=False, default=False)
    auto_validated = Column(Boolean, nullable=False, default=False)
    validation_report = Column(JSON, nullable=True)  # results of content_safety + privacy + sandbox exec
    source_url = Column(String, nullable=True)  # GitHub URL if imported

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    vendor = relationship("Vendor", back_populates="listings")
    workspace = relationship("Workspace")
    files = relationship("MarketplaceFile", back_populates="listing", cascade="all, delete-orphan")
    evidence_packages = relationship("EvidencePackage", back_populates="listing", cascade="all, delete-orphan")
