"""Initial migration - create all tables

Revision ID: fa1c0174b21d
Revises:
Create Date: 2026-02-18 08:31:41.373094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fa1c0174b21d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abuse_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("abuse_type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_abuse_logs_created_at"),
        "abuse_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_abuse_logs_ip_address"),
        "abuse_logs",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_abuse_logs_user_id"), "abuse_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_abuse_logs_workspace_id"),
        "abuse_logs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "apps",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apps_slug"), "apps", ["slug"], unique=True)
    op.create_table(
        "incident_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("incident_type", sa.String(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", "CRITICAL", name="incidentseverity"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "INVESTIGATING",
                "RESOLVED",
                "CLOSED",
                name="incidentstatus",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_logs_created_at"),
        "incident_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_logs_workspace_id"),
        "incident_logs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("billing_email", sa.String(length=255), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("tax_id", sa.String(length=50), nullable=True),
        sa.Column("max_workspaces", sa.String(), nullable=True),
        sa.Column("max_users", sa.String(), nullable=True),
        sa.Column("feature_flags", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_id"), "organizations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.create_table(
        "security_audit_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_category", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_audit_logs_created_at"),
        "security_audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_audit_logs_event_type"),
        "security_audit_logs",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_audit_logs_user_id"),
        "security_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_audit_logs_workspace_id"),
        "security_audit_logs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True
    )
    op.create_table(
        "anomalies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column(
            "anomaly_type",
            sa.Enum(
                "COST_SPIKE",
                "TRAFFIC_SPIKE",
                "QUALITY_DEGRADATION",
                "LATENCY_SPIKE",
                "FAILURE_RATE_INCREASE",
                "UNUSUAL_PATTERN",
                name="anomalytype",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", "CRITICAL", name="anomalyseverity"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DETECTED",
                "INVESTIGATING",
                "REMEDIATED",
                "FALSE_POSITIVE",
                "RESOLVED",
                name="anomalystatus",
            ),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("detected_by", sa.String(), nullable=False),
        sa.Column("confidence_score", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("baseline_value", sa.String(), nullable=True),
        sa.Column("actual_value", sa.String(), nullable=True),
        sa.Column("deviation_percent", sa.String(), nullable=True),
        sa.Column("remediated_at", sa.DateTime(), nullable=True),
        sa.Column("remediation_action", sa.Text(), nullable=True),
        sa.Column("remediation_result", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomalies_detected_at"),
        "anomalies",
        ["detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anomalies_workspace_id"),
        "anomalies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "app_workspaces",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("app_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["apps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "workspace_id", name="uq_app_workspace"),
    )
    op.create_index(
        op.f("ix_app_workspaces_app_id"),
        "app_workspaces",
        ["app_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_app_workspaces_workspace_id"),
        "app_workspaces",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("s3_bucket", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(
        op.f("ix_assets_workspace_id"),
        "assets",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "budgets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("budget_type", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column(
            "current_spend", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("forecast_exhaustion_date", sa.DateTime(), nullable=True),
        sa.Column("forecast_updated_at", sa.DateTime(), nullable=True),
        sa.Column("alerts_sent", sa.JSON(), nullable=True),
        sa.Column("last_alert_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budgets_workspace_id"),
        "budgets",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_name"), "categories", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_categories_slug"), "categories", ["slug"], unique=False
    )
    op.create_index(
        op.f("ix_categories_workspace_id"),
        "categories",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "cost_allocations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("operation_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=True),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column(
            "allocated_cost", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "base_cost", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "markup_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "final_cost", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column("allocation_method", sa.String(), nullable=False),
        sa.Column("allocation_rule_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_allocations_client_id"),
        "cost_allocations",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_allocations_operation_id"),
        "cost_allocations",
        ["operation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_allocations_project_id"),
        "cost_allocations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_allocations_workspace_id"),
        "cost_allocations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "cost_predictions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_output_tokens", sa.Integer(), nullable=False),
        sa.Column("input_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "predicted_cost", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "confidence_lower",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
        ),
        sa.Column(
            "confidence_upper",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
        ),
        sa.Column(
            "actual_cost", sa.Numeric(precision=10, scale=6), nullable=True
        ),
        sa.Column("actual_input_tokens", sa.Integer(), nullable=True),
        sa.Column("actual_output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "prediction_error_percent",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column("was_within_confidence", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("actualized_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_predictions_created_at"),
        "cost_predictions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_predictions_workspace_id"),
        "cost_predictions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("service_type", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "FAILED", name="deploymentstatus"),
            nullable=False,
        ),
        sa.Column("deployed_at", sa.DateTime(), nullable=False),
        sa.Column("last_health_check", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_region"), "deployments", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_deployments_workspace_id"),
        "deployments",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum("TRANSCRIBE", "EXPORT", name="jobtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="jobstatus"
            ),
            nullable=False,
        ),
        sa.Column("input_data", sa.String(), nullable=True),
        sa.Column("output_data", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("requested_provider", sa.String(), nullable=True),
        sa.Column("resolved_provider", sa.String(), nullable=True),
        sa.Column("policy_id", sa.String(), nullable=True),
        sa.Column("policy_version", sa.String(), nullable=True),
        sa.Column("policy_enforcement", sa.String(), nullable=True),
        sa.Column("policy_reason", sa.String(), nullable=True),
        sa.Column("was_fallback", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jobs_workspace_id"), "jobs", ["workspace_id"], unique=False
    )
    op.create_table(
        "ml_models",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("training_samples", sa.Integer(), nullable=False),
        sa.Column("test_samples", sa.Integer(), nullable=True),
        sa.Column("mape", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("accuracy", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("feature_list", sa.JSON(), nullable=True),
        sa.Column("trained_at", sa.DateTime(), nullable=False),
        sa.Column("training_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_production", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ml_models_workspace_id"),
        "ml_models",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "organization_sso_providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider_type", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(length=500), nullable=False),
        sa.Column("client_secret", sa.Text(), nullable=False),
        sa.Column("issuer_url", sa.String(length=500), nullable=True),
        sa.Column(
            "authorization_endpoint", sa.String(length=500), nullable=True
        ),
        sa.Column("token_endpoint", sa.String(length=500), nullable=True),
        sa.Column("userinfo_endpoint", sa.String(length=500), nullable=True),
        sa.Column("jwks_uri", sa.String(length=500), nullable=True),
        sa.Column("saml_entity_id", sa.String(length=500), nullable=True),
        sa.Column("saml_metadata_url", sa.String(length=500), nullable=True),
        sa.Column("saml_certificate", sa.Text(), nullable=True),
        sa.Column("attribute_mapping", sa.Text(), nullable=True),
        sa.Column("role_mapping", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("auto_provision", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_sso_providers_id"),
        "organization_sso_providers",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sso_providers_organization_id"),
        "organization_sso_providers",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "routing_decisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("operation_id", sa.String(), nullable=True),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("constraints_json", sa.Text(), nullable=True),
        sa.Column("selected_provider", sa.String(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column(
            "expected_cost", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "expected_quality", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("expected_latency_ms", sa.Integer(), nullable=True),
        sa.Column("alternatives_json", sa.Text(), nullable=True),
        sa.Column(
            "actual_cost", sa.Numeric(precision=10, scale=6), nullable=True
        ),
        sa.Column(
            "actual_quality", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("actual_latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "cost_saved_vs_default",
            sa.Numeric(precision=10, scale=6),
            nullable=True,
        ),
        sa.Column("quality_met_threshold", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("actualized_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routing_decisions_created_at"),
        "routing_decisions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_routing_decisions_operation_id"),
        "routing_decisions",
        ["operation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_routing_decisions_workspace_id"),
        "routing_decisions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "routing_policies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("strategy", sa.String(), nullable=False),
        sa.Column("constraints_json", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routing_policies_workspace_id"),
        "routing_policies",
        ["workspace_id"],
        unique=True,
    )
    op.create_table(
        "routing_strategies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("preferred_provider", sa.String(), nullable=True),
        sa.Column("provider_weights", sa.JSON(), nullable=True),
        sa.Column(
            "exploration_rate", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("strategy_type", sa.String(), nullable=False),
        sa.Column("constraints_json", sa.Text(), nullable=True),
        sa.Column("total_samples", sa.Integer(), nullable=False),
        sa.Column("learning_samples", sa.Integer(), nullable=False),
        sa.Column(
            "best_provider_reward",
            sa.Numeric(precision=10, scale=6),
            nullable=True,
        ),
        sa.Column(
            "avg_cost_saved", sa.Numeric(precision=10, scale=6), nullable=True
        ),
        sa.Column(
            "avg_quality_improvement",
            sa.Numeric(precision=5, scale=4),
            nullable=True,
        ),
        sa.Column("avg_latency_reduction_ms", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routing_strategies_operation_type"),
        "routing_strategies",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_routing_strategies_workspace_id"),
        "routing_strategies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "savings_reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("report_type", sa.String(), nullable=False),
        sa.Column(
            "total_savings", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "baseline_cost", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "actual_cost", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column(
            "savings_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("latency_reduction_ms", sa.Integer(), nullable=True),
        sa.Column(
            "cache_hit_rate_improvement",
            sa.Numeric(precision=5, scale=4),
            nullable=True,
        ),
        sa.Column("operations_count", sa.Integer(), nullable=False),
        sa.Column("breakdown_by_operation", sa.JSON(), nullable=True),
        sa.Column("breakdown_by_provider", sa.JSON(), nullable=True),
        sa.Column(
            "projected_next_month_savings",
            sa.Numeric(precision=10, scale=6),
            nullable=True,
        ),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("generated_by", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savings_reports_workspace_id"),
        "savings_reports",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "scim_groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scim_resource_type", sa.String(length=50), nullable=False),
        sa.Column("scim_schema", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scim_groups_external_id"),
        "scim_groups",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scim_groups_id"), "scim_groups", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scim_groups_workspace_id"),
        "scim_groups",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "scim_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("allowed_operations", sa.Text(), nullable=True),
        sa.Column("allowed_attributes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scim_tokens_id"), "scim_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scim_tokens_token_hash"),
        "scim_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_scim_tokens_workspace_id"),
        "scim_tokens",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)
    op.create_index(
        op.f("ix_tags_workspace_id"), "tags", ["workspace_id"], unique=False
    )
    op.create_table(
        "traffic_patterns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("pattern_type", sa.String(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=True),
        sa.Column("pattern_data", sa.JSON(), nullable=False),
        sa.Column(
            "avg_requests_per_hour",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column("peak_hour", sa.Integer(), nullable=True),
        sa.Column("peak_day", sa.Integer(), nullable=True),
        sa.Column("predicted_spike_time", sa.DateTime(), nullable=True),
        sa.Column(
            "predicted_spike_multiplier",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column("predicted_requests", sa.Integer(), nullable=True),
        sa.Column("samples_used", sa.Integer(), nullable=False),
        sa.Column(
            "confidence_score", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_traffic_patterns_workspace_id"),
        "traffic_patterns",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("gems", sa.Integer(), nullable=False),
        sa.Column("total_live_sessions", sa.Integer(), nullable=False),
        sa.Column("total_live_minutes", sa.Integer(), nullable=False),
        sa.Column("total_live_viewers", sa.Integer(), nullable=False),
        sa.Column("monthly_live_score", sa.Integer(), nullable=False),
        sa.Column("last_month_rank", sa.Integer(), nullable=True),
        sa.Column("free_month_earned", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_monthly_live_score"),
        "users",
        ["monthly_live_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_workspace_id"), "users", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_retention_policies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("policy_type", sa.String(length=50), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("retention_action", sa.String(length=20), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=True),
        sa.Column("exceptions", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system_default", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("total_processed", sa.Integer(), nullable=False),
        sa.Column("total_deleted", sa.Integer(), nullable=False),
        sa.Column("total_archived", sa.Integer(), nullable=False),
        sa.Column("total_anonymized", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_retention_policies_id"),
        "workspace_retention_policies",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_retention_policies_policy_type"),
        "workspace_retention_policies",
        ["policy_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_retention_policies_workspace_id"),
        "workspace_retention_policies",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "workspace_secrets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("secret_name", sa.String(), nullable=False),
        sa.Column("encrypted_value", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id",
            "provider",
            "secret_name",
            name="uq_workspace_provider_secret",
        ),
    )
    op.create_index(
        op.f("ix_workspace_secrets_provider"),
        "workspace_secrets",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_secrets_workspace_id"),
        "workspace_secrets",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "ai_audit_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("output_hash", sa.String(), nullable=False),
        sa.Column("input_preview", sa.Text(), nullable=True),
        sa.Column("output_preview", sa.Text(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("tokens_input", sa.Integer(), nullable=True),
        sa.Column("tokens_output", sa.Integer(), nullable=True),
        sa.Column(
            "actual_quality", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("actual_latency_ms", sa.Integer(), nullable=True),
        sa.Column("routing_decision_id", sa.String(), nullable=True),
        sa.Column("routing_reasoning", sa.Text(), nullable=True),
        sa.Column("pii_detected", sa.Boolean(), nullable=False),
        sa.Column("pii_types", sa.JSON(), nullable=True),
        sa.Column("sensitive_data_flags", sa.JSON(), nullable=True),
        sa.Column("log_hash", sa.String(), nullable=False),
        sa.Column("previous_log_hash", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["routing_decision_id"],
            ["routing_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_audit_logs_created_at"),
        "ai_audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_audit_logs_operation_type"),
        "ai_audit_logs",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_audit_logs_provider"),
        "ai_audit_logs",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_audit_logs_user_id"),
        "ai_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_audit_logs_workspace_id"),
        "ai_audit_logs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("actor_user_id", sa.String(), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=True),
        sa.Column("actor_ip_address", sa.String(length=45), nullable=True),
        sa.Column("actor_user_agent", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.String(), nullable=True),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("old_values", sa.Text(), nullable=True),
        sa.Column("new_values", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("status_code", sa.String(length=10), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_actor_user_id"),
        "audit_events",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_event_type"),
        "audit_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_id"), "audit_events", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"),
        "audit_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"),
        "audit_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_request_id"),
        "audit_events",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_resource_id"),
        "audit_events",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_resource_type"),
        "audit_events",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_workspace_id"),
        "audit_events",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "content",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("VIDEO", "LIVE", "PHOTO", name="contenttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                "PROCESSING",
                name="contentstatus",
            ),
            nullable=False,
        ),
        sa.Column("category_id", sa.String(), nullable=True),
        sa.Column("source_api", sa.String(), nullable=True),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("favorite_count", sa.Integer(), nullable=False),
        sa.Column("quality", sa.String(), nullable=True),
        sa.Column("tags_json", sa.JSON(), nullable=True),
        sa.Column("performers_json", sa.JSON(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.String(), nullable=True),
        sa.Column("approved_by_admin_id", sa.String(), nullable=True),
        sa.Column("approval_notes", sa.Text(), nullable=True),
        sa.Column("approval_date", sa.DateTime(), nullable=True),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("live_viewers_count", sa.Integer(), nullable=False),
        sa.Column("live_started_at", sa.DateTime(), nullable=True),
        sa.Column("live_ended_at", sa.DateTime(), nullable=True),
        sa.Column("live_stream_url", sa.String(), nullable=True),
        sa.Column("live_chat_enabled", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_category_id"),
        "content",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_is_live"), "content", ["is_live"], unique=False
    )
    op.create_index(
        op.f("ix_content_published_at"),
        "content",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_status"), "content", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_content_title"), "content", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_content_uploaded_by_user_id"),
        "content",
        ["uploaded_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_workspace_id"),
        "content",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "exports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column(
            "format",
            sa.Enum("JSON", "CSV", "ZIP", name="exportformat"),
            nullable=False,
        ),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("s3_bucket", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(
        op.f("ix_exports_job_id"), "exports", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_exports_workspace_id"),
        "exports",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "game_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("current_level", sa.Integer(), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("player_level", sa.Integer(), nullable=False),
        sa.Column("coins", sa.Integer(), nullable=False),
        sa.Column("total_games_played", sa.Integer(), nullable=False),
        sa.Column("total_wins", sa.Integer(), nullable=False),
        sa.Column("total_losses", sa.Integer(), nullable=False),
        sa.Column("best_streak", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("unlocked_particles", sa.JSON(), nullable=True),
        sa.Column("unlocked_themes", sa.JSON(), nullable=True),
        sa.Column("unlocked_powerups", sa.JSON(), nullable=True),
        sa.Column("sound_enabled", sa.Boolean(), nullable=False),
        sa.Column("music_enabled", sa.Boolean(), nullable=False),
        sa.Column("vibration_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_profiles_user_id"),
        "game_profiles",
        ["user_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_game_profiles_workspace_id"),
        "game_profiles",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "monthly_leaderboards",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("live_sessions_count", sa.Integer(), nullable=False),
        sa.Column("total_live_minutes", sa.Integer(), nullable=False),
        sa.Column("total_viewers", sa.Integer(), nullable=False),
        sa.Column("total_gems_earned", sa.Integer(), nullable=False),
        sa.Column("total_gifts_received", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("reward_claimed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monthly_leaderboards_month"),
        "monthly_leaderboards",
        ["month"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monthly_leaderboards_rank"),
        "monthly_leaderboards",
        ["rank"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monthly_leaderboards_total_score"),
        "monthly_leaderboards",
        ["total_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monthly_leaderboards_user_id"),
        "monthly_leaderboards",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monthly_leaderboards_workspace_id"),
        "monthly_leaderboards",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monthly_leaderboards_year"),
        "monthly_leaderboards",
        ["year"],
        unique=False,
    )
    op.create_table(
        "scim_group_members",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("external_user_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["scim_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scim_group_members_group_id"),
        "scim_group_members",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scim_group_members_id"),
        "scim_group_members",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scim_group_members_user_id"),
        "scim_group_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "scim_group_workspace_roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("workspace_role", sa.String(length=50), nullable=False),
        sa.Column("auto_assign", sa.Boolean(), nullable=False),
        sa.Column("auto_remove", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["scim_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scim_group_workspace_roles_group_id"),
        "scim_group_workspace_roles",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scim_group_workspace_roles_id"),
        "scim_group_workspace_roles",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scim_group_workspace_roles_workspace_id"),
        "scim_group_workspace_roles",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "FREE", "BASIC", "PREMIUM", "VIP", name="subscriptiontier"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "CANCELLED",
                "EXPIRED",
                "PENDING",
                "TRIAL",
                name="subscriptionstatus",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("price_period", sa.Float(), nullable=False),
        sa.Column("billing_period_days", sa.Integer(), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("payment_provider", sa.String(), nullable=True),
        sa.Column(
            "payment_provider_subscription_id", sa.String(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_expires_at"),
        "subscriptions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_status"),
        "subscriptions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_tier"), "subscriptions", ["tier"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"),
        "subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_workspace_id"),
        "subscriptions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "transcripts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcripts_asset_id"),
        "transcripts",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcripts_workspace_id"),
        "transcripts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("sso_provider_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=False),
        sa.Column("external_email", sa.String(length=255), nullable=True),
        sa.Column("external_username", sa.String(length=255), nullable=True),
        sa.Column("external_name", sa.String(length=500), nullable=True),
        sa.Column("attributes", sa.Text(), nullable=True),
        sa.Column("last_authenticated_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sso_provider_id"],
            ["organization_sso_providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_identities_external_id"),
        "user_identities",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_identities_id"), "user_identities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_identities_sso_provider_id"),
        "user_identities",
        ["sso_provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_identities_user_id"),
        "user_identities",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "workspace_memberships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("permissions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("invited_by", sa.String(), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("preferences", sa.Text(), nullable=True),
        sa.Column("notifications", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_memberships_id"),
        "workspace_memberships",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_memberships_user_id"),
        "workspace_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_memberships_workspace_id"),
        "workspace_memberships",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "ai_feedback",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("audit_log_id", sa.String(), nullable=True),
        sa.Column("operation_id", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column(
            "quality_score", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("is_correct", sa.Integer(), nullable=True),
        sa.Column("feedback_text", sa.Text(), nullable=True),
        sa.Column("feedback_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_log_id"],
            ["ai_audit_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_feedback_audit_log_id"),
        "ai_feedback",
        ["audit_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_feedback_created_at"),
        "ai_feedback",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_feedback_operation_id"),
        "ai_feedback",
        ["operation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_feedback_workspace_id"),
        "ai_feedback",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "content_tags",
        sa.Column("content_id", sa.String(), nullable=False),
        sa.Column("tag_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("content_id", "tag_id"),
    )
    op.create_table(
        "game_achievements",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("achievement_id", sa.String(), nullable=False),
        sa.Column("achievement_type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("is_unlocked", sa.Boolean(), nullable=False),
        sa.Column("coins_reward", sa.Integer(), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("items_reward", sa.JSON(), nullable=True),
        sa.Column("unlocked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["game_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_achievements_achievement_id"),
        "game_achievements",
        ["achievement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_achievements_profile_id"),
        "game_achievements",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "game_leaderboards",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("leaderboard_type", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("level_reached", sa.Integer(), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("game_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["game_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_leaderboards_leaderboard_type"),
        "game_leaderboards",
        ["leaderboard_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_leaderboards_profile_id"),
        "game_leaderboards",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_leaderboards_score"),
        "game_leaderboards",
        ["score"],
        unique=False,
    )
    op.create_table(
        "game_level_progress",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("level_number", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("is_perfect", sa.Boolean(), nullable=False),
        sa.Column("best_score", sa.Integer(), nullable=False),
        sa.Column("best_time", sa.Float(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("coins_earned", sa.Integer(), nullable=False),
        sa.Column("xp_earned", sa.Integer(), nullable=False),
        sa.Column("first_completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_played_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["game_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_level_progress_level_number"),
        "game_level_progress",
        ["level_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_level_progress_profile_id"),
        "game_level_progress",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "game_purchases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("product_type", sa.String(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("receipt_data", sa.Text(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_consumed", sa.Boolean(), nullable=False),
        sa.Column("coins_granted", sa.Integer(), nullable=False),
        sa.Column("items_granted", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["game_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_purchases_product_id"),
        "game_purchases",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_purchases_profile_id"),
        "game_purchases",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_purchases_transaction_id"),
        "game_purchases",
        ["transaction_id"],
        unique=True,
    )
    op.create_table(
        "live_streams",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("content_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("rtmp_url", sa.String(), nullable=True),
        sa.Column("stream_key", sa.String(), nullable=True),
        sa.Column("playback_url", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("peak_viewers", sa.Integer(), nullable=False),
        sa.Column("current_viewers", sa.Integer(), nullable=False),
        sa.Column("total_views", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("gifts_received", sa.Integer(), nullable=False),
        sa.Column("gems_earned", sa.Integer(), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("chat_enabled", sa.Boolean(), nullable=False),
        sa.Column("comments_enabled", sa.Boolean(), nullable=False),
        sa.Column("gifts_enabled", sa.Boolean(), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_live_streams_status"),
        "live_streams",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_streams_user_id"),
        "live_streams",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_streams_workspace_id"),
        "live_streams",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("subscription_id", sa.String(), nullable=True),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "FAILED",
                "REFUNDED",
                "CANCELLED",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.Column("payment_provider", sa.String(), nullable=False),
        sa.Column("provider_payment_id", sa.String(), nullable=True),
        sa.Column("provider_customer_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payments_provider_payment_id"),
        "payments",
        ["provider_payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payments_status"), "payments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_payments_subscription_id"),
        "payments",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_workspace_id"),
        "payments",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "live_stream_gifts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("stream_id", sa.String(), nullable=False),
        sa.Column("sender_user_id", sa.String(), nullable=False),
        sa.Column("gift_type", sa.String(), nullable=False),
        sa.Column("gift_value", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["live_streams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_live_stream_gifts_sender_user_id"),
        "live_stream_gifts",
        ["sender_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_stream_gifts_stream_id"),
        "live_stream_gifts",
        ["stream_id"],
        unique=False,
    )
    op.create_table(
        "live_stream_viewers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("stream_id", sa.String(), nullable=False),
        sa.Column("viewer_user_id", sa.String(), nullable=True),
        sa.Column("viewer_ip", sa.String(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("left_at", sa.DateTime(), nullable=True),
        sa.Column("watch_duration_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["live_streams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["viewer_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_live_stream_viewers_stream_id"),
        "live_stream_viewers",
        ["stream_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_stream_viewers_viewer_user_id"),
        "live_stream_viewers",
        ["viewer_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_live_stream_viewers_viewer_user_id"),
        table_name="live_stream_viewers",
    )
    op.drop_index(
        op.f("ix_live_stream_viewers_stream_id"),
        table_name="live_stream_viewers",
    )
    op.drop_table("live_stream_viewers")
    op.drop_index(
        op.f("ix_live_stream_gifts_stream_id"), table_name="live_stream_gifts"
    )
    op.drop_index(
        op.f("ix_live_stream_gifts_sender_user_id"),
        table_name="live_stream_gifts",
    )
    op.drop_table("live_stream_gifts")
    op.drop_index(op.f("ix_payments_workspace_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_subscription_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(
        op.f("ix_payments_provider_payment_id"), table_name="payments"
    )
    op.drop_table("payments")
    op.drop_index(
        op.f("ix_live_streams_workspace_id"), table_name="live_streams"
    )
    op.drop_index(op.f("ix_live_streams_user_id"), table_name="live_streams")
    op.drop_index(op.f("ix_live_streams_status"), table_name="live_streams")
    op.drop_table("live_streams")
    op.drop_index(
        op.f("ix_game_purchases_transaction_id"), table_name="game_purchases"
    )
    op.drop_index(
        op.f("ix_game_purchases_profile_id"), table_name="game_purchases"
    )
    op.drop_index(
        op.f("ix_game_purchases_product_id"), table_name="game_purchases"
    )
    op.drop_table("game_purchases")
    op.drop_index(
        op.f("ix_game_level_progress_profile_id"),
        table_name="game_level_progress",
    )
    op.drop_index(
        op.f("ix_game_level_progress_level_number"),
        table_name="game_level_progress",
    )
    op.drop_table("game_level_progress")
    op.drop_index(
        op.f("ix_game_leaderboards_score"), table_name="game_leaderboards"
    )
    op.drop_index(
        op.f("ix_game_leaderboards_profile_id"), table_name="game_leaderboards"
    )
    op.drop_index(
        op.f("ix_game_leaderboards_leaderboard_type"),
        table_name="game_leaderboards",
    )
    op.drop_table("game_leaderboards")
    op.drop_index(
        op.f("ix_game_achievements_profile_id"), table_name="game_achievements"
    )
    op.drop_index(
        op.f("ix_game_achievements_achievement_id"),
        table_name="game_achievements",
    )
    op.drop_table("game_achievements")
    op.drop_table("content_tags")
    op.drop_index(
        op.f("ix_ai_feedback_workspace_id"), table_name="ai_feedback"
    )
    op.drop_index(
        op.f("ix_ai_feedback_operation_id"), table_name="ai_feedback"
    )
    op.drop_index(op.f("ix_ai_feedback_created_at"), table_name="ai_feedback")
    op.drop_index(
        op.f("ix_ai_feedback_audit_log_id"), table_name="ai_feedback"
    )
    op.drop_table("ai_feedback")
    op.drop_index(
        op.f("ix_workspace_memberships_workspace_id"),
        table_name="workspace_memberships",
    )
    op.drop_index(
        op.f("ix_workspace_memberships_user_id"),
        table_name="workspace_memberships",
    )
    op.drop_index(
        op.f("ix_workspace_memberships_id"), table_name="workspace_memberships"
    )
    op.drop_table("workspace_memberships")
    op.drop_index(
        op.f("ix_user_identities_user_id"), table_name="user_identities"
    )
    op.drop_index(
        op.f("ix_user_identities_sso_provider_id"),
        table_name="user_identities",
    )
    op.drop_index(op.f("ix_user_identities_id"), table_name="user_identities")
    op.drop_index(
        op.f("ix_user_identities_external_id"), table_name="user_identities"
    )
    op.drop_table("user_identities")
    op.drop_index(
        op.f("ix_transcripts_workspace_id"), table_name="transcripts"
    )
    op.drop_index(op.f("ix_transcripts_asset_id"), table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_index(
        op.f("ix_subscriptions_workspace_id"), table_name="subscriptions"
    )
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_tier"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(
        op.f("ix_subscriptions_expires_at"), table_name="subscriptions"
    )
    op.drop_table("subscriptions")
    op.drop_index(
        op.f("ix_scim_group_workspace_roles_workspace_id"),
        table_name="scim_group_workspace_roles",
    )
    op.drop_index(
        op.f("ix_scim_group_workspace_roles_id"),
        table_name="scim_group_workspace_roles",
    )
    op.drop_index(
        op.f("ix_scim_group_workspace_roles_group_id"),
        table_name="scim_group_workspace_roles",
    )
    op.drop_table("scim_group_workspace_roles")
    op.drop_index(
        op.f("ix_scim_group_members_user_id"), table_name="scim_group_members"
    )
    op.drop_index(
        op.f("ix_scim_group_members_id"), table_name="scim_group_members"
    )
    op.drop_index(
        op.f("ix_scim_group_members_group_id"), table_name="scim_group_members"
    )
    op.drop_table("scim_group_members")
    op.drop_index(
        op.f("ix_monthly_leaderboards_year"), table_name="monthly_leaderboards"
    )
    op.drop_index(
        op.f("ix_monthly_leaderboards_workspace_id"),
        table_name="monthly_leaderboards",
    )
    op.drop_index(
        op.f("ix_monthly_leaderboards_user_id"),
        table_name="monthly_leaderboards",
    )
    op.drop_index(
        op.f("ix_monthly_leaderboards_total_score"),
        table_name="monthly_leaderboards",
    )
    op.drop_index(
        op.f("ix_monthly_leaderboards_rank"), table_name="monthly_leaderboards"
    )
    op.drop_index(
        op.f("ix_monthly_leaderboards_month"),
        table_name="monthly_leaderboards",
    )
    op.drop_table("monthly_leaderboards")
    op.drop_index(
        op.f("ix_game_profiles_workspace_id"), table_name="game_profiles"
    )
    op.drop_index(op.f("ix_game_profiles_user_id"), table_name="game_profiles")
    op.drop_table("game_profiles")
    op.drop_index(op.f("ix_exports_workspace_id"), table_name="exports")
    op.drop_index(op.f("ix_exports_job_id"), table_name="exports")
    op.drop_table("exports")
    op.drop_index(op.f("ix_content_workspace_id"), table_name="content")
    op.drop_index(op.f("ix_content_uploaded_by_user_id"), table_name="content")
    op.drop_index(op.f("ix_content_title"), table_name="content")
    op.drop_index(op.f("ix_content_status"), table_name="content")
    op.drop_index(op.f("ix_content_published_at"), table_name="content")
    op.drop_index(op.f("ix_content_is_live"), table_name="content")
    op.drop_index(op.f("ix_content_category_id"), table_name="content")
    op.drop_table("content")
    op.drop_index(
        op.f("ix_audit_events_workspace_id"), table_name="audit_events"
    )
    op.drop_index(
        op.f("ix_audit_events_resource_type"), table_name="audit_events"
    )
    op.drop_index(
        op.f("ix_audit_events_resource_id"), table_name="audit_events"
    )
    op.drop_index(
        op.f("ix_audit_events_request_id"), table_name="audit_events"
    )
    op.drop_index(
        op.f("ix_audit_events_organization_id"), table_name="audit_events"
    )
    op.drop_index(
        op.f("ix_audit_events_occurred_at"), table_name="audit_events"
    )
    op.drop_index(op.f("ix_audit_events_id"), table_name="audit_events")
    op.drop_index(
        op.f("ix_audit_events_event_type"), table_name="audit_events"
    )
    op.drop_index(
        op.f("ix_audit_events_actor_user_id"), table_name="audit_events"
    )
    op.drop_table("audit_events")
    op.drop_index(
        op.f("ix_ai_audit_logs_workspace_id"), table_name="ai_audit_logs"
    )
    op.drop_index(op.f("ix_ai_audit_logs_user_id"), table_name="ai_audit_logs")
    op.drop_index(
        op.f("ix_ai_audit_logs_provider"), table_name="ai_audit_logs"
    )
    op.drop_index(
        op.f("ix_ai_audit_logs_operation_type"), table_name="ai_audit_logs"
    )
    op.drop_index(
        op.f("ix_ai_audit_logs_created_at"), table_name="ai_audit_logs"
    )
    op.drop_table("ai_audit_logs")
    op.drop_index(
        op.f("ix_workspace_secrets_workspace_id"),
        table_name="workspace_secrets",
    )
    op.drop_index(
        op.f("ix_workspace_secrets_provider"), table_name="workspace_secrets"
    )
    op.drop_table("workspace_secrets")
    op.drop_index(
        op.f("ix_workspace_retention_policies_workspace_id"),
        table_name="workspace_retention_policies",
    )
    op.drop_index(
        op.f("ix_workspace_retention_policies_policy_type"),
        table_name="workspace_retention_policies",
    )
    op.drop_index(
        op.f("ix_workspace_retention_policies_id"),
        table_name="workspace_retention_policies",
    )
    op.drop_table("workspace_retention_policies")
    op.drop_index(op.f("ix_users_workspace_id"), table_name="users")
    op.drop_index(op.f("ix_users_monthly_live_score"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_traffic_patterns_workspace_id"), table_name="traffic_patterns"
    )
    op.drop_table("traffic_patterns")
    op.drop_index(op.f("ix_tags_workspace_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(
        op.f("ix_scim_tokens_workspace_id"), table_name="scim_tokens"
    )
    op.drop_index(op.f("ix_scim_tokens_token_hash"), table_name="scim_tokens")
    op.drop_index(op.f("ix_scim_tokens_id"), table_name="scim_tokens")
    op.drop_table("scim_tokens")
    op.drop_index(
        op.f("ix_scim_groups_workspace_id"), table_name="scim_groups"
    )
    op.drop_index(op.f("ix_scim_groups_id"), table_name="scim_groups")
    op.drop_index(op.f("ix_scim_groups_external_id"), table_name="scim_groups")
    op.drop_table("scim_groups")
    op.drop_index(
        op.f("ix_savings_reports_workspace_id"), table_name="savings_reports"
    )
    op.drop_table("savings_reports")
    op.drop_index(
        op.f("ix_routing_strategies_workspace_id"),
        table_name="routing_strategies",
    )
    op.drop_index(
        op.f("ix_routing_strategies_operation_type"),
        table_name="routing_strategies",
    )
    op.drop_table("routing_strategies")
    op.drop_index(
        op.f("ix_routing_policies_workspace_id"), table_name="routing_policies"
    )
    op.drop_table("routing_policies")
    op.drop_index(
        op.f("ix_routing_decisions_workspace_id"),
        table_name="routing_decisions",
    )
    op.drop_index(
        op.f("ix_routing_decisions_operation_id"),
        table_name="routing_decisions",
    )
    op.drop_index(
        op.f("ix_routing_decisions_created_at"), table_name="routing_decisions"
    )
    op.drop_table("routing_decisions")
    op.drop_index(
        op.f("ix_organization_sso_providers_organization_id"),
        table_name="organization_sso_providers",
    )
    op.drop_index(
        op.f("ix_organization_sso_providers_id"),
        table_name="organization_sso_providers",
    )
    op.drop_table("organization_sso_providers")
    op.drop_index(op.f("ix_ml_models_workspace_id"), table_name="ml_models")
    op.drop_table("ml_models")
    op.drop_index(op.f("ix_jobs_workspace_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        op.f("ix_deployments_workspace_id"), table_name="deployments"
    )
    op.drop_index(op.f("ix_deployments_region"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(
        op.f("ix_cost_predictions_workspace_id"), table_name="cost_predictions"
    )
    op.drop_index(
        op.f("ix_cost_predictions_created_at"), table_name="cost_predictions"
    )
    op.drop_table("cost_predictions")
    op.drop_index(
        op.f("ix_cost_allocations_workspace_id"), table_name="cost_allocations"
    )
    op.drop_index(
        op.f("ix_cost_allocations_project_id"), table_name="cost_allocations"
    )
    op.drop_index(
        op.f("ix_cost_allocations_operation_id"), table_name="cost_allocations"
    )
    op.drop_index(
        op.f("ix_cost_allocations_client_id"), table_name="cost_allocations"
    )
    op.drop_table("cost_allocations")
    op.drop_index(op.f("ix_categories_workspace_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_budgets_workspace_id"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_assets_workspace_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(
        op.f("ix_app_workspaces_workspace_id"), table_name="app_workspaces"
    )
    op.drop_index(
        op.f("ix_app_workspaces_app_id"), table_name="app_workspaces"
    )
    op.drop_table("app_workspaces")
    op.drop_index(op.f("ix_anomalies_workspace_id"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_detected_at"), table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(
        op.f("ix_security_audit_logs_workspace_id"),
        table_name="security_audit_logs",
    )
    op.drop_index(
        op.f("ix_security_audit_logs_user_id"),
        table_name="security_audit_logs",
    )
    op.drop_index(
        op.f("ix_security_audit_logs_event_type"),
        table_name="security_audit_logs",
    )
    op.drop_index(
        op.f("ix_security_audit_logs_created_at"),
        table_name="security_audit_logs",
    )
    op.drop_table("security_audit_logs")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(
        op.f("ix_incident_logs_workspace_id"), table_name="incident_logs"
    )
    op.drop_index(
        op.f("ix_incident_logs_created_at"), table_name="incident_logs"
    )
    op.drop_table("incident_logs")
    op.drop_index(op.f("ix_apps_slug"), table_name="apps")
    op.drop_table("apps")
    op.drop_index(op.f("ix_abuse_logs_workspace_id"), table_name="abuse_logs")
    op.drop_index(op.f("ix_abuse_logs_user_id"), table_name="abuse_logs")
    op.drop_index(op.f("ix_abuse_logs_ip_address"), table_name="abuse_logs")
    op.drop_index(op.f("ix_abuse_logs_created_at"), table_name="abuse_logs")
    op.drop_table("abuse_logs")
    # ### end Alembic commands ###
