"""Curated real marketplace catalog entries.

These are external, publicly available products/actions. They are not Veklom-owned
SKUs and should only point to real source or marketplace URLs that users can use.
"""
from __future__ import annotations

from copy import deepcopy


REAL_MARKETPLACE_CATALOG = [
    {
        "id": "github-actions-checkout",
        "vendor_id": "external-actions",
        "title": "Checkout",
        "provider": "GitHub Actions",
        "category": "SDK Extensions",
        "description": "Official GitHub action for checking out a repository inside a workflow. Use it as the trusted base step before Veklom policy and deployment gates.",
        "positioning": "Official GitHub action for checking out repositories in workflows. Veklom can wrap it with governed policy checks before builds, scans, and deploys run.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.9,
        "installs": 7800,
        "badges": ["Verified creator", "Official GitHub", "CI foundation"],
        "featured": True,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/checkout",
        "use_url": "https://github.com/marketplace/actions/checkout",
        "usage": "uses: actions/checkout@v6",
        "status": "active",
    },
    {
        "id": "github-actions-setup-node",
        "vendor_id": "external-actions",
        "title": "Setup Node.js Environment",
        "provider": "GitHub Actions",
        "category": "SDK Extensions",
        "description": "Official setup-node action for Node.js CI/CD workflows.",
        "positioning": "Sets up Node.js in GitHub Actions so Veklom-governed build, test, and release workflows can run consistently.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 6800,
        "badges": ["Verified creator", "Node.js", "CI"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/setup-node-js-environment",
        "use_url": "https://github.com/marketplace/actions/setup-node-js-environment",
        "usage": "uses: actions/setup-node@v6",
        "status": "active",
    },
    {
        "id": "github-actions-setup-python",
        "vendor_id": "external-actions",
        "title": "Setup Python",
        "provider": "GitHub Actions",
        "category": "SDK Extensions",
        "description": "Official setup-python action for Python build and test workflows.",
        "positioning": "Installs Python on GitHub runners so Veklom can govern test, package, and API-client workflows for backend teams.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 6400,
        "badges": ["Official GitHub", "Python", "CI"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/actions/setup-python",
        "use_url": "https://github.com/actions/setup-python",
        "usage": "uses: actions/setup-python@v6",
        "status": "active",
    },
    {
        "id": "docker-build-push-action",
        "vendor_id": "external-docker",
        "title": "Build and Push Docker Images",
        "provider": "Docker",
        "category": "Deployment Images",
        "description": "Official Docker action for building and pushing images with Buildx and BuildKit.",
        "positioning": "Builds and pushes container images with BuildKit. Veklom can place governance, vulnerability, and approval gates before production image release.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "docker"],
        "rating": 4.9,
        "installs": 5900,
        "badges": ["Verified creator", "Docker", "BuildKit"],
        "featured": True,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/build-and-push-docker-images",
        "use_url": "https://github.com/marketplace/actions/build-and-push-docker-images",
        "usage": "uses: docker/build-push-action@v7",
        "status": "active",
    },
    {
        "id": "aws-configure-credentials",
        "vendor_id": "external-aws",
        "title": "Configure AWS Credentials",
        "provider": "AWS",
        "category": "Connectors",
        "description": "Official AWS action for configuring AWS credentials in GitHub Actions, including OIDC-based role assumption.",
        "positioning": "Connects GitHub Actions to AWS using role-based credentials. Veklom can govern who may deploy, from which repo, and under which policy.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "aws"],
        "rating": 4.8,
        "installs": 2900,
        "badges": ["Verified creator", "AWS OIDC", "Deploy"],
        "featured": True,
        "compliance": ["SOC2", "HIPAA"],
        "source_url": "https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions",
        "use_url": "https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions",
        "usage": "uses: aws-actions/configure-aws-credentials@v6",
        "status": "active",
    },
    {
        "id": "hashicorp-setup-terraform",
        "vendor_id": "external-hashicorp",
        "title": "HashiCorp Setup Terraform",
        "provider": "HashiCorp",
        "category": "Pipelines",
        "description": "HashiCorp action that installs and configures Terraform CLI in GitHub Actions workflows.",
        "positioning": "Runs Terraform plans and applies in CI/CD. Veklom can add approval gates, policy checks, and signed audit records to infrastructure changes.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "terraform"],
        "rating": 4.8,
        "installs": 1500,
        "badges": ["Verified creator", "Terraform", "IaC"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/hashicorp-setup-terraform",
        "use_url": "https://github.com/marketplace/actions/hashicorp-setup-terraform",
        "usage": "uses: hashicorp/setup-terraform@v4",
        "status": "active",
    },
    {
        "id": "github-codeql-action",
        "vendor_id": "external-github-security",
        "title": "CodeQL Action",
        "provider": "GitHub Security",
        "category": "Compliance Packs",
        "description": "GitHub CodeQL action for semantic code analysis and code scanning uploads.",
        "positioning": "Runs semantic security analysis and uploads results to GitHub code scanning. Veklom can require clean CodeQL gates before governed deploys.",
        "price": "Free for eligible repos",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 1500,
        "badges": ["GitHub Security", "Code scanning", "SAST"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/github/codeql-action",
        "use_url": "https://github.com/github/codeql-action",
        "usage": "uses: github/codeql-action/init@v4",
        "status": "active",
    },
    {
        "id": "snyk-github-action",
        "vendor_id": "external-snyk",
        "title": "Snyk",
        "provider": "Snyk",
        "category": "Compliance Packs",
        "description": "Snyk GitHub Actions for vulnerability checks across supported ecosystems.",
        "positioning": "Checks projects for vulnerabilities. Veklom can treat Snyk results as a governed release condition with audit evidence.",
        "price": "Free / paid plans",
        "price_cents": 0,
        "currency": "usd",
        "billing": "external",
        "install": "GitHub Action",
        "target": ["github", "snyk"],
        "rating": 4.7,
        "installs": 606,
        "badges": ["Verified creator", "Vulnerability scan", "SCA"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/snyk",
        "use_url": "https://github.com/marketplace/actions/snyk",
        "usage": "uses: snyk/actions/node@master",
        "status": "active",
    },
    {
        "id": "step-security-harden-runner",
        "vendor_id": "external-step-security",
        "title": "Harden-Runner",
        "provider": "StepSecurity",
        "category": "Pipelines",
        "description": "Runtime security monitoring and egress control for GitHub-hosted and self-hosted runners.",
        "positioning": "Monitors CI/CD runner process, file, and network behavior. Veklom can use it as runtime evidence for governed deployment workflows.",
        "price": "Free / paid plans",
        "price_cents": 0,
        "currency": "usd",
        "billing": "external",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 920,
        "badges": ["Verified creator", "Runner security", "Egress audit"],
        "featured": True,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/harden-runner",
        "use_url": "https://github.com/marketplace/actions/harden-runner",
        "usage": "uses: step-security/harden-runner@v2",
        "status": "active",
    },
    {
        "id": "slack-send-github-action",
        "vendor_id": "external-slack",
        "title": "Slack: Send to Slack",
        "provider": "Slack",
        "category": "Connectors",
        "description": "Slack GitHub Action for posting workflow output or calling Slack APIs from CI/CD.",
        "positioning": "Sends CI/CD status, approval events, and incident notifications into Slack. Veklom can route governed decision events into team channels.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "slack"],
        "rating": 4.7,
        "installs": 1200,
        "badges": ["Verified creator", "Notifications", "Workflow Builder"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/slackapi/slack-github-action",
        "use_url": "https://docs.slack.dev/tools/slack-github-action/",
        "usage": "uses: slackapi/slack-github-action@v3",
        "status": "active",
    },
]


def real_marketplace_catalog() -> list[dict]:
    """Return a copy so route handlers can enrich safely.

    Install and rating counts are not returned for curated external listings
    unless Veklom has a live source for that metric. The marketplace should
    only show factual source, billing, and usage data as available today.
    """
    catalog = deepcopy(REAL_MARKETPLACE_CATALOG)
    for item in catalog:
        item["source_verified"] = True
        item["verification_note"] = "Official public source verified by Veklom catalog review."
        item["rating_avg"] = 0
        item["rating_count"] = 0
        item["install_count"] = 0
        item.pop("rating", None)
        item.pop("installs", None)
    return catalog
