"""Curated real marketplace catalog entries.

These are external, publicly available products/actions. They are not Veklom-owned
SKUs and should only point to real source or marketplace URLs that users can use.
"""
from __future__ import annotations

from copy import deepcopy


REAL_MARKETPLACE_CATALOG = [
    {
        "id": "github-actions-checkout",
        "vendor_id": "external-actions",
        "title": "Checkout",
        "provider": "GitHub Actions",
        "category": "SDK Extensions",
        "description": "Official GitHub action for checking out a repository inside a workflow. Use it as the trusted base step before Veklom policy and deployment gates.",
        "positioning": "Official GitHub action for checking out repositories in workflows. Veklom can wrap it with governed policy checks before builds, scans, and deploys run.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.9,
        "installs": 7800,
        "badges": ["Verified creator", "Official GitHub", "CI foundation"],
        "featured": True,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/checkout",
        "use_url": "https://github.com/marketplace/actions/checkout",
        "usage": "uses: actions/checkout@v6",
        "status": "active",
    },
    {
        "id": "github-actions-setup-node",
        "vendor_id": "external-actions",
        "title": "Setup Node.js Environment",
        "provider": "GitHub Actions",
        "category": "SDK Extensions",
        "description": "Official setup-node action for Node.js CI/CD workflows.",
        "positioning": "Sets up Node.js in GitHub Actions so Veklom-governed build, test, and release workflows can run consistently.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 6800,
        "badges": ["Verified creator", "Node.js", "CI"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/setup-node-js-environment",
        "use_url": "https://github.com/marketplace/actions/setup-node-js-environment",
        "usage": "uses: actions/setup-node@v6",
        "status": "active",
    },
    {
        "id": "github-actions-setup-python",
        "vendor_id": "external-actions",
        "title": "Setup Python",
        "provider": "GitHub Actions",
        "category": "SDK Extensions",
        "description": "Official setup-python action for Python build and test workflows.",
        "positioning": "Installs Python on GitHub runners so Veklom can govern test, package, and API-client workflows for backend teams.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 6400,
        "badges": ["Official GitHub", "Python", "CI"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/actions/setup-python",
        "use_url": "https://github.com/actions/setup-python",
        "usage": "uses: actions/setup-python@v6",
        "status": "active",
    },
    {
        "id": "docker-build-push-action",
        "vendor_id": "external-docker",
        "title": "Build and Push Docker Images",
        "provider": "Docker",
        "category": "Deployment Images",
        "description": "Official Docker action for building and pushing images with Buildx and BuildKit.",
        "positioning": "Builds and pushes container images with BuildKit. Veklom can place governance, vulnerability, and approval gates before production image release.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "docker"],
        "rating": 4.9,
        "installs": 5900,
        "badges": ["Verified creator", "Docker", "BuildKit"],
        "featured": True,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/build-and-push-docker-images",
        "use_url": "https://github.com/marketplace/actions/build-and-push-docker-images",
        "usage": "uses: docker/build-push-action@v7",
        "status": "active",
    },
    {
        "id": "aws-configure-credentials",
        "vendor_id": "external-aws",
        "title": "Configure AWS Credentials",
        "provider": "AWS",
        "category": "Connectors",
        "description": "Official AWS action for configuring AWS credentials in GitHub Actions, including OIDC-based role assumption.",
        "positioning": "Connects GitHub Actions to AWS using role-based credentials. Veklom can govern who may deploy, from which repo, and under which policy.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "aws"],
        "rating": 4.8,
        "installs": 2900,
        "badges": ["Verified creator", "AWS OIDC", "Deploy"],
        "featured": True,
        "compliance": ["SOC2", "HIPAA"],
        "source_url": "https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions",
        "use_url": "https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions",
        "usage": "uses: aws-actions/configure-aws-credentials@v6",
        "status": "active",
    },
    {
        "id": "hashicorp-setup-terraform",
        "vendor_id": "external-hashicorp",
        "title": "HashiCorp Setup Terraform",
        "provider": "HashiCorp",
        "category": "Pipelines",
        "description": "HashiCorp action that installs and configures Terraform CLI in GitHub Actions workflows.",
        "positioning": "Runs Terraform plans and applies in CI/CD. Veklom can add approval gates, policy checks, and signed audit records to infrastructure changes.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "terraform"],
        "rating": 4.8,
        "installs": 1500,
        "badges": ["Verified creator", "Terraform", "IaC"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/hashicorp-setup-terraform",
        "use_url": "https://github.com/marketplace/actions/hashicorp-setup-terraform",
        "usage": "uses: hashicorp/setup-terraform@v4",
        "status": "active",
    },
    {
        "id": "github-codeql-action",
        "vendor_id": "external-github-security",
        "title": "CodeQL Action",
        "provider": "GitHub Security",
        "category": "Compliance Packs",
        "description": "GitHub CodeQL action for semantic code analysis and code scanning uploads.",
        "positioning": "Runs semantic security analysis and uploads results to GitHub code scanning. Veklom can require clean CodeQL gates before governed deploys.",
        "price": "Free for eligible repos",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 1500,
        "badges": ["GitHub Security", "Code scanning", "SAST"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/github/codeql-action",
        "use_url": "https://github.com/github/codeql-action",
        "usage": "uses: github/codeql-action/init@v4",
        "status": "active",
    },
    {
        "id": "snyk-github-action",
        "vendor_id": "external-snyk",
        "title": "Snyk",
        "provider": "Snyk",
        "category": "Compliance Packs",
        "description": "Snyk GitHub Actions for vulnerability checks across supported ecosystems.",
        "positioning": "Checks projects for vulnerabilities. Veklom can treat Snyk results as a governed release condition with audit evidence.",
        "price": "Free / paid plans",
        "price_cents": 0,
        "currency": "usd",
        "billing": "external",
        "install": "GitHub Action",
        "target": ["github", "snyk"],
        "rating": 4.7,
        "installs": 606,
        "badges": ["Verified creator", "Vulnerability scan", "SCA"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/snyk",
        "use_url": "https://github.com/marketplace/actions/snyk",
        "usage": "uses: snyk/actions/node@master",
        "status": "active",
    },
    {
        "id": "step-security-harden-runner",
        "vendor_id": "external-step-security",
        "title": "Harden-Runner",
        "provider": "StepSecurity",
        "category": "Pipelines",
        "description": "Runtime security monitoring and egress control for GitHub-hosted and self-hosted runners.",
        "positioning": "Monitors CI/CD runner process, file, and network behavior. Veklom can use it as runtime evidence for governed deployment workflows.",
        "price": "Free / paid plans",
        "price_cents": 0,
        "currency": "usd",
        "billing": "external",
        "install": "GitHub Action",
        "target": ["github"],
        "rating": 4.8,
        "installs": 920,
        "badges": ["Verified creator", "Runner security", "Egress audit"],
        "featured": True,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/marketplace/actions/harden-runner",
        "use_url": "https://github.com/marketplace/actions/harden-runner",
        "usage": "uses: step-security/harden-runner@v2",
        "status": "active",
    },
    {
        "id": "slack-send-github-action",
        "vendor_id": "external-slack",
        "title": "Slack: Send to Slack",
        "provider": "Slack",
        "category": "Connectors",
        "description": "Slack GitHub Action for posting workflow output or calling Slack APIs from CI/CD.",
        "positioning": "Sends CI/CD status, approval events, and incident notifications into Slack. Veklom can route governed decision events into team channels.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "GitHub Action",
        "target": ["github", "slack"],
        "rating": 4.7,
        "installs": 1200,
        "badges": ["Verified creator", "Notifications", "Workflow Builder"],
        "featured": False,
        "compliance": ["SOC2"],
        "source_url": "https://github.com/slackapi/slack-github-action",
        "use_url": "https://docs.slack.dev/tools/slack-github-action/",
        "usage": "uses: slackapi/slack-github-action@v3",
        "status": "active",
    },
]

# ── LockerSphere verticals ────────────────────────────────────────────────────
# First-party products distributed through the Veklom Marketplace.  Each
# vertical is a white-label AI security backend with industry-specific
# compliance, security policies, and AI capabilities.

LOCKERSPHERE_CATALOG = [
    {
        "id": "lockersphere-hospital",
        "vendor_id": "veklom-first-party",
        "title": "LockerSphere Hospital",
        "provider": "LockerSphere",
        "category": "Managed Services",
        "description": "HIPAA-grade AI security for global healthcare. PHI detection & redaction, HL7/FHIR gateway, clinical AI guardrails, and 7-year audit trails.",
        "positioning": "White-label AI security platform built for hospitals and health systems — HIPAA, HITECH, GDPR, and HL7-FHIR compliant out of the box.",
        "price": "Enterprise",
        "price_cents": 0,
        "currency": "usd",
        "billing": "enterprise",
        "install": "One-Click Install",
        "target": ["api", "workspace"],
        "listing_type": "agent",
        "tags": ["lockersphere", "ai-security", "white-label", "hipaa", "healthcare", "phi-protection", "clinical-ai"],
        "badges": ["First Party", "HIPAA", "HITECH", "GDPR", "HL7-FHIR"],
        "featured": True,
        "compliance": ["HIPAA", "HITECH", "GDPR", "HL7-FHIR", "PIPEDA", "LGPD"],
        "source_url": "https://github.com/reprewindai-dev/lockerphycer",
        "use_url": "/api/v1/verticals/hospital",
        "status": "active",
    },
    {
        "id": "lockersphere-bank",
        "vendor_id": "veklom-first-party",
        "title": "LockerSphere Bank",
        "provider": "LockerSphere",
        "category": "Managed Services",
        "description": "PCI-DSS v4.0 compliant AI security for financial institutions. Transaction fraud detection, AML screening, SWIFT message security, SOX compliance.",
        "positioning": "White-label AI security for banks and financial services — PCI-DSS, SOX, Basel III, and AML-KYC compliant. Real-time fraud detection and regulatory reporting.",
        "price": "Enterprise",
        "price_cents": 0,
        "currency": "usd",
        "billing": "enterprise",
        "install": "One-Click Install",
        "target": ["api", "workspace"],
        "listing_type": "agent",
        "tags": ["lockersphere", "ai-security", "white-label", "pci-dss", "banking", "fraud-detection", "aml-kyc"],
        "badges": ["First Party", "PCI-DSS v4.0", "SOX", "Basel III", "AML-KYC"],
        "featured": True,
        "compliance": ["PCI-DSS v4.0", "SOX", "Basel III", "AML-KYC", "SWIFT-CSP", "GDPR", "GLBA"],
        "source_url": "https://github.com/reprewindai-dev/lockerphycer",
        "use_url": "/api/v1/verticals/bank",
        "status": "active",
    },
    {
        "id": "lockersphere-insurance",
        "vendor_id": "veklom-first-party",
        "title": "LockerSphere Insurance",
        "provider": "LockerSphere",
        "category": "Managed Services",
        "description": "AI security and compliance for insurance carriers. Claims fraud detection, actuarial model governance, underwriting fairness monitoring, catastrophe modeling.",
        "positioning": "White-label AI security for insurers — Solvency II, IFRS-17, EU AI Act, and NAIC compliant. Automated claims fraud detection and actuarial governance.",
        "price": "Enterprise",
        "price_cents": 0,
        "currency": "usd",
        "billing": "enterprise",
        "install": "One-Click Install",
        "target": ["api", "workspace"],
        "listing_type": "agent",
        "tags": ["lockersphere", "ai-security", "white-label", "solvency-ii", "claims-fraud", "actuarial", "underwriting"],
        "badges": ["First Party", "Solvency II", "IFRS-17", "EU AI Act", "NAIC"],
        "featured": True,
        "compliance": ["Solvency II", "NAIC Model Laws", "IFRS-17", "GDPR", "CCPA", "EU AI Act"],
        "source_url": "https://github.com/reprewindai-dev/lockerphycer",
        "use_url": "/api/v1/verticals/insurance",
        "status": "active",
    },
    {
        "id": "lockersphere-content-creator",
        "vendor_id": "veklom-first-party",
        "title": "LockerSphere Content Creator",
        "provider": "LockerSphere",
        "category": "Managed Services",
        "description": "AI security for creators, studios, and media. Content fingerprinting, deepfake detection, DMCA management, harassment shield, and revenue protection.",
        "positioning": "White-label AI security for content creators and media companies — DMCA, FTC, COPPA, and DSA compliant. Protect your content, brand, and revenue.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "One-Click Install",
        "target": ["api", "workspace"],
        "listing_type": "agent",
        "tags": ["lockersphere", "ai-security", "white-label", "dmca", "content-moderation", "deepfake-detection", "creator"],
        "badges": ["First Party", "DMCA", "FTC", "COPPA", "DSA"],
        "featured": True,
        "compliance": ["DMCA", "FTC Guidelines", "GDPR", "DSA", "COPPA"],
        "source_url": "https://github.com/reprewindai-dev/lockerphycer",
        "use_url": "/api/v1/verticals/content_creator",
        "status": "active",
    },
    {
        "id": "lockersphere-general",
        "vendor_id": "veklom-first-party",
        "title": "LockerSphere",
        "provider": "LockerSphere",
        "category": "Managed Services",
        "description": "AI-powered security that works out of the box. Threat detection, anomaly detection, vulnerability scanning, and content safety — no configuration needed.",
        "positioning": "General-purpose AI security platform — SOC 2, ISO 27001, and GDPR compliant. Zero-config deployment with threat detection, anomaly monitoring, and audit logging.",
        "price": "Free",
        "price_cents": 0,
        "currency": "usd",
        "billing": "free",
        "install": "One-Click Install",
        "target": ["api", "workspace"],
        "listing_type": "agent",
        "tags": ["lockersphere", "ai-security", "white-label", "soc2", "threat-detection", "anomaly-detection"],
        "badges": ["First Party", "SOC 2", "ISO 27001", "GDPR"],
        "featured": True,
        "compliance": ["SOC 2 Type II", "GDPR", "ISO 27001"],
        "source_url": "https://github.com/reprewindai-dev/lockerphycer",
        "use_url": "/api/v1/verticals/general",
        "status": "active",
    },
]


def real_marketplace_catalog() -> list[dict]:
    """Return a copy so route handlers can enrich safely.

    Includes both external curated listings and first-party LockerSphere
    verticals.  Install and rating counts are not returned for curated
    external listings unless Veklom has a live source for that metric.
    """
    catalog = deepcopy(REAL_MARKETPLACE_CATALOG + LOCKERSPHERE_CATALOG)
    for item in catalog:
        item["source_verified"] = True
        if item.get("vendor_id") == "veklom-first-party":
            item["verification_note"] = "First-party LockerSphere product by Veklom."
        else:
            item["verification_note"] = "Official public source verified by Veklom catalog review."
        item["rating_avg"] = 0
        item["rating_count"] = 0
        item["install_count"] = 0
        item.pop("rating", None)
        item.pop("installs", None)
    return catalog
